### ISSUE TITLE
Remove explicit padding

### ISSUE THREAD

**Issue by gitman88** [krasserm/super-resolution#10]
I am curious about the reason for padding in the test phase. What is the general purpose for this?

`pad = Lambda(lambda x: K.in_train_phase(x, tf.pad(x, tf.constant([[0, 0], [2, 2], [2, 2], [0, 0]]), 'SYMMETRIC')))`

And there is also this function for training `def _crop_hr_in_training(hr, sr):` 

    margin = (tf.shape(hr)[1] - tf.shape(sr)[1]) // 2

    # crop only if margin > 0
    hr_crop = tf.cond(tf.equal(margin, 0),
                      lambda: hr,
                      lambda: hr[:, margin:-margin, margin:-margin, :])

    hr = K.in_train_phase(hr_crop, hr)
    hr.uses_learning_phase = True
    return hr, sr`

Where it states that 

`   Remove margin of size scale*2 from hr in training phase.
    The margin is computed from size difference of hr and sr
    so that no explicit scale parameter is needed. This is only
    needed for WDSR models.` 

I assume these two code snippets are related. My question is why not just train och test on the same image sizes instead of removing margins and padding in different phases?

Thanks!

**Comment by krasserm** [comment]
Would like to leave the ticket open as I plan to work on it ...

**Comment by krasserm** [comment]
Will be covered in context of #18

**Comment by krasserm** [comment]
Implemented with https://github.com/krasserm/super-resolution/commit/d6b56b3796c3d726fe355ab8848abeff890ca590
