### ISSUE TITLE
Inference at 2X scale

### ISSUE THREAD

**Issue by PraveenAsh** [krasserm/super-resolution#11]
The demo.py allows us to scale to 4X. But how to infer it to 2X scale?

**Comment by krasserm** [comment]
Just use 2x pre-trained model.

**Comment by PraveenAsh** [comment]
Oh! My bad. Didn't the documentation thoroughly. Thanks!

**Comment by PraveenAsh** [comment]
I think in the arg-parser we need to add another argument to receive the scale value for demo.py for convenience sake.

**Comment by krasserm** [comment]
Why? The scale is specified implicitly with the --model option. Using an x2 model, for example, implies scale 2. What is missing?
