### ISSUE TITLE
Unable to reproduce experimental results

### ISSUE THREAD

**Issue by huziye** [krasserm/super-resolution#12]
I can't reproduce the results of the experiment based on the instructions you provided, using your code and the same data set.

**Comment by krasserm** [comment]
Do you mind sharing the commands you ran and the results you got :wink: ?

**Comment by huziye** [comment]
python train.py --dataset ./DIV2K_BIN --outdir ./output --profile wdsr-a-16 --scale 2
python evaluate.py --dataset ./DIV2K_BIN -i ./output/dir/models -o eval.json
Your result is 34.68,but I get Best PSNR = 34.6105 and Best PSNR = 34.5994 in my two repeated experiments.

**Comment by krasserm** [comment]
Thanks, try training with 400 or 500 epochs (default is 300). Maybe I forgot adding that to the documented command.

**Comment by krasserm** [comment]
Please re-open if you still have problems to reproduce
