### ISSUE TITLE
training my own data very slowly

### ISSUE THREAD

**Issue by yanmenglu** [krasserm/super-resolution#21]
Hi, kraserm, thank you for your great work. 
But when I training my own data, It is very slow. I have 4303 train data, and  I set iter_steps 4000 per epoch, the epoch is 300, the batch size is 32. After 20 hours, only training 2000 iterations in the one epoch.
I used one GPU (GTX1080 11G).  and the GPU-util is all zero percent.  so I think maybe some bottleneck in the data load. or another something leads to so slowly. Could you help me to boost the training speed? thank you very much.

**Comment by krasserm** [comment]
I can only help if you share all modifications you've made

**Comment by yanmenglu** [comment]
Thank you very much, I have solved this problem. this problem is because of my data not stored in the SSD.

**Comment by Flyzzz** [comment]
你好，我想问一下怎么用自己的照片制作数据集？

**Comment by krasserm** [comment]
@Flyzzz you need to your create a own `tf.data.Dataset` that generates LR/HR image pairs (see [data.py](https://github.com/krasserm/super-resolution/blob/master/data.py) for details). The DIV2K dataset already contains LR/HR pairs. If you have a dataset with HR images only, you need to downsample the HR images yourself to get LR images.

**Comment by Flyzzz** [comment]
thank you! @krasserm

**Comment by clodiamery** [comment]
Please can you help, how can train the model on my own dataset?  @yanmenglu
