### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (Cast_80:0) to a numpy array.

### ISSUE THREAD

**Issue by ShaniaShan** [krasserm/super-resolution#35]
When I am running the examples, attained super resolution image can not be show because it is a symbolic Tensor. The detail error is given as the following: 

NotImplementedError                       Traceback (most recent call last)
<ipython-input-75-cfc5562b598d> in <module>()
      9 lr = load_image('superresolution/demo/0851x4-crop.png')
     10 sr = resolve_single(model, lr)
---> 11 plot_sample(lr,sr)
     12 
     13 type(sr)

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py in __array__(self)
    734   def __array__(self):
    735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
--> 736                               " array.".format(self.name))
    737 
    738   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (Cast_80:0) to a numpy array.

**Comment by krasserm** [comment]
I cannot reproduce that. Please provide more details:

- which notebook have you used for running the example? If you have used a custom notebook/script please attach it (wonder if you have disabled eager execution).
- list of installed packages in your environment.

**Comment by ShaniaShan** [comment]
Thank Mr. Krasser for your response. I ran the EDSR example with pre-trained weights by using Google Colab. I followed your given codes:

from model import resolve_single
from model.edsr import edsr
from utils import load_image, plot_sample

model = edsr(scale=4, num_res_blocks=16)
model.load_weights('weights/edsr-16-x4/weights.h5')

lr = load_image('demo/0851x4-crop.png')
sr = resolve_single(model, lr)

plot_sample(lr, sr)


When I ran the example, I got the errors as the following:
NotImplementedError                       Traceback (most recent call last)
<ipython-input-8-bd7018a02dfa> in <module>()
     10 #tf.dtypes.cast(sr, tf.float32)
     11 sr = resolve_single(model, lr)
---> 12 plot_sample(lr,sr)
     13 
     

________________________________________
8 frames
________________________________________
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py in __array__(self)
    734   def __array__(self):
    735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
--> 736                               " array.".format(self.name))
    737 
    738   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (strided_slice_1:0) to a numpy array.

**Comment by krasserm** [comment]
Do you mind sharing the Colab notebook here so that I can reproduce the error?

**Comment by ShaniaShan** [comment]
Thanks a lot!
This is my Colab notebook link: 
https://colab.research.google.com/drive/1UtlpG8YCtIouwUT7_e-hNB8G2qg7HTpk

**Comment by krasserm** [comment]
It seems you're using the default Tensorflow version in Colab which is 1.x. This project requires 2.0 though. You can enable Tensorflow 2.0 with `%tensorflow_version 2.x` in the notebook. I just tried that with your notebook (after some minor changes) and it works as expected.

![sr](https://user-images.githubusercontent.com/202907/70027692-ffe05a80-15a2-11ea-8486-7daf10b9fdaa.png)

**Comment by ShaniaShan** [comment]
Thank you so much!

**Comment by sandhya9173** [comment]
Hi

I want some information on how to generate a model GAN network you save directly generator.h5, I am sending one image that much bad quality also I want clear image please can you help in this process, I want some information, it's important for me.

![e13617_0bcfe97a906147cbac3b94861013d875_mv2](https://user-images.githubusercontent.com/57871594/76704678-ae4a7e80-6700-11ea-99a5-858f9adaa8e4.png)
