### ISSUE TITLE
GAN is now "tearing" my images

### ISSUE THREAD

**Issue by Jurph** [krasserm/super-resolution#42]
ISR with weights='gan' was working fine -- all models were working great -- but then recently all of my images are getting messed up with identical "stairstep" or tearing errors. I don't know what this artifact is usually called so I'm struggling to google for answers. 

I've tried swapping out cv2.imread() and cv2.imwrite() for the PIL.Image.open() and PIL.Image.save() functions with no effect. It looks like either the initial numpy conversion or the `predict()` function are undercounting pixels, and when it gets written to a 4x image there's not enough width in a row to fill out the image. Is there some chunking code in ISR that could be broken? 

![cat_gan4x](https://user-images.githubusercontent.com/7751563/75251412-8a061c80-57a8-11ea-961c-49940ed3e593.png)
![cat](https://user-images.githubusercontent.com/7751563/75251416-8b374980-57a8-11ea-945c-1ae025afe7e9.jpg)

**Comment by krasserm** [comment]
Not sure I follow. This project doesn't even use OpenCV so what do you mean with 

> swapping out cv2.imread() and cv2.imwrite()

and what with `weights='gan'`? Can you please elaborate?

**Comment by Jurph** [comment]
...I just realized I entered this issue on the completely wrong project. My mistake.
