### ISSUE TITLE
number of input channels does not match corresponding dimension of filter, 4 != 3

### ISSUE THREAD

**Issue by lesthad666** [krasserm/super-resolution#44]
When I try to run "resolve_and_plot('demo/othercat.png')" command with another image that is hosted in the demo folder, it does not work. Other questions I have, only accept png format? And how big is the image?

**Comment by krasserm** [comment]
You can use any format as long as the image is a 3-channel RGB image. The image you're trying to load is a PNG with an additional alpha channel and this channel must be removed:

```
from model import resolve_single
from utils import plot_sample
from PIL import Image

model = ...
lr = np.array(Image.open(''demo/othercat.png').convert('RGB))
sr = resolve_single(model, lr)
plot_sample(lr, sr)
```

Please re-open if you find further issues.
