### ISSUE TITLE
gan_generator.h5 code i want 

### ISSUE THREAD

**Issue by sandhya9173** [krasserm/super-resolution#46]
Still my images its coming low quality only please can you provide me Generator code I have to check
![low_quality](https://user-images.githubusercontent.com/57871594/76931033-d9ee8400-690d-11ea-84f4-2918976bf7a7.png)

**Comment by krasserm** [comment]
Your LR image seems to have strong JPG compression artifacts. The published models have not been trained to remove these artifacts. Instead high-quality HR images were transformed to LR images via bicubic downscaling (see DIV2K dataset) and used for model training. See also https://github.com/krasserm/super-resolution/issues/19 for a related discussion. If you want a model to deal with JPG compression artifacts you'd need to create your own dataset for model training.

**Comment by sandhya9173** [comment]
thank you for giving information, I have only low-quality images I don't have any high-quality image but, I saw your code their you sending DIV2K_high_train Images but I don't have I want to train my images my low to high-quality resolution please can you help me. 
![pic](https://user-images.githubusercontent.com/57871594/77154551-eddae700-6ac1-11ea-8dcb-e26b95c58c80.jpg)
