### ISSUE TITLE
error in preprocess_input

### ISSUE THREAD

**Issue by vibss2397** [krasserm/super-resolution#53]
I keep on getting an error when i was running vgg19.preprocess_input -

This is currently happening in tf 2.0.0

`
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: Const:0
`

**Comment by krasserm** [comment]
It would be helpful if you could provide some details what you've run. A notebook as is in the repo, some custom code ...?

**Comment by vibss2397** [comment]
hey @krasserm, so i used the same train_step function, same model functions, same loss functions but in content loss, the error seems to be in the line to calculate preprocess_input for vgg 19, when it reaches this line inside train step function i am getting the error -
`
AttributeError: in converted code:

    <ipython-input-147-55ebc38c8d11>:29 content_loss  *
        sr = tf.keras.applications.vgg19.preprocess_input(sr)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/keras/applications/__init__.py:49 wrapper
        return base_fun(*args, **kwargs)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/keras/applications/vgg19.py:44 preprocess_input
        return vgg19.preprocess_input(*args, **kwargs)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/keras_applications/imagenet_utils.py:195 preprocess_input
        mode=mode, **kwargs)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/keras_applications/imagenet_utils.py:151 _preprocess_symbolic_input
        x = backend.bias_add(x, _IMAGENET_MEAN, data_format)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/keras/backend.py:5531 bias_add
        x = nn.bias_add(x, bias, data_format='NHWC')
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/ops/nn_ops.py:2718 bias_add
        return gen_nn_ops.bias_add(value, bias, data_format=data_format, name=name)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/ops/gen_nn_ops.py:761 bias_add
        "BiasAdd", value=value, bias=bias, data_format=data_format, name=name)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/framework/op_def_library.py:793 _apply_op_helper
        op_def=op_def)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/framework/func_graph.py:544 create_op
        inp = self.capture(inp)
    /share/pkg.7/tensorflow/2.0.0/install/lib/SCC/../python3.6-gpu/site-packages/tensorflow_core/python/framework/func_graph.py:604 capture
        inner_graph = inner_graph.outer_graph

    AttributeError: 'FuncGraph' object has no attribute 'outer_graph'
`

and using it outside train_step function, just to figure out what is not working, i get -

`
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: Const:0
`

**Comment by vibss2397** [comment]
Actually, I think it is fixed now :
I was trying it yesterday in tensorflow 2.0.0 and it did not seem to work, but today i tried it in tensorflow 2.1.0 and it started working, must be something in tf 2.0
