### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by ruanjiyang** [krasserm/super-resolution#55]
I try to scale one photo by  " resolve_and_plot('demo/2.jpg')", and get the error like this:
ResourceExhaustedError: OOM when allocating tensor with shape[1,666,1000,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Conv2D]

how to fix this? thanks lot!

**Comment by ruanjiyang** [comment]
the file is example-srgan.ipynb

**Comment by ruanjiyang** [comment]
my gpu is GTX1080 /8G

**Comment by krasserm** [comment]
When running the demo in `example-srgan.ipynb` it requires 8003 MB of the available 8119 MB of a GTX 1080 (8 GB). So if you have another process running on this card, for example X server or whatever, you probably won't have enough memory for running the SRGAN example. This is not really an issue of the code in this repo, hence I'm closing this ticket. You could try running the example with smaller test images (e.g. by cropping the demo images).

**Comment by gastoneb** [comment]
> This is not really an issue of the code in this repo

Sorry I don't mean to be rude and I appreciate all the work gone into this project, but if it can't handle a 666x1000 image on an 8GB card then it _is_ an issue of the code, because it won't scale to any practical application on consumer hardware. How would you handle even a modest smartphone image?

I was going to try processing my image in 512*512 blocks and fusing the downscaled chunks together. It would just need a wrapper around `resolve_single()`. Hopefully that works.

**Comment by krasserm** [comment]
I recommend using either a EDSR or WDSR model as generator for [fine-tuning with SRGAN](https://github.com/krasserm/super-resolution#srgan-for-fine-tuning-edsr-and-wdsr-models). Fine-tuned EDSR and WDSR generators can be download [here](https://martin-krasser.de/sisr/weights-article-2.tar.gz) (see also [this article](https://krasserm.github.io/2019/09/04/super-resolution/)). These generators are able to process a 1024*669 image (just tried with an example image of that size) on an 8 GB card and yield also better results than the default SRResNet.

The code provided in this repository is meant to be a reference implementation of the corresponding papers and I didn't make any attempts to provide a version that scales to much larger images under resource constraints. So a conclusion on whether this is an issue of the provided code or not depends on the scope and goal of this project. 

I certainly see the usefulness to implement support for scaling to larger images (e.g. by [patching and recombination](https://github.com/idealo/image-super-resolution#large-image-inference)) and any contribution in this context is very welcome. @gastoneb, if you need any support implementing it for this repo, I'm happy to help.
