### ISSUE TITLE
Why does Colab keep crashing when training srgan

### ISSUE THREAD

**Issue by ShaniaShan** [krasserm/super-resolution#58]
I am trying to train srgan on Colab. The session keeps crashing and restarting. Here are the log files from recent crash.

**Comment by krasserm** [comment]
Seems you forgot to upload the log file(s).

**Comment by ShaniaShan** [comment]
Mr. Krasser, thank you for your responding me. I got the reason of this issue. It was caused by my large 3D dataset.
