### ISSUE TITLE
load_model error

### ISSUE THREAD

**Issue by vvhj** [krasserm/super-resolution#7]
hello! when i load WDSR model trained by myself ,it shows : 
"NameError: name 'tf' is not defined"
in "pad = Lambda(lambda x: K.in_train_phase(x, tf.pad(x, tf.constant([[0, 0], [2, 2], [2, 2], [0, 0]]), 'SYMMETRIC')))"

**Comment by krasserm** [comment]
Use 

```python
from model import load_model
```

**Comment by krasserm** [comment]
Closing this issue. Please re-open if the error persists.
