### ISSUE TITLE
the python code for downloading the training and validation datasets is incomplete

### ISSUE THREAD

**Issue by mamanso** [krasserm/super-resolution#75]
Could you complete it?

**Comment by krasserm** [comment]
Can you please be more specific what exactly is missing?

**Comment by mamanso** [comment]
the content of the loop (for lr, hr in train_ds:) that handles the pairs of images to save them,

###
from data import DIV2K

train_loader = DIV2K(scale=4,             # 2, 3, 4 or 8
                     downgrade='bicubic', # 'bicubic', 'unknown', 'mild' or 'difficult' 
                     subset='train')      # Training dataset are images 001 - 800
                     
# Create a tf.data.Dataset          
train_ds = train_loader.dataset(batch_size=16,         # batch size as described in the EDSR and WDSR papers
                                random_transform=True, # random crop, flip, rotate as described in the EDSR paper
                                repeat_count=None)     # repeat iterating over training images indefinitely

# Iterate over LR/HR image pairs                                
for lr, hr in train_ds:
    # ....

**Comment by krasserm** [comment]
There's no need to save images inside the loop. Saving is automatically done behind the scenes by the `DIV2K` class. Within the for loop you just use the (saved) images for training, validation, ... like in [this example](https://github.com/krasserm/super-resolution/blob/fa72c09cf056db8f376af7595ae0f7274f514daa/train.py#L47).

**Comment by mamanso** [comment]
Thank you, I understood that these were examples of data downloads for training and validation, not as part of the full code.
