### ISSUE TITLE
Train on custom dataset 

### ISSUE THREAD

**Issue by gitman88** [krasserm/super-resolution#8]
First of all, thanks for sharing this repository. Very interesting!

I was wondering if it is possible to train or test the models on other datasets, like Set5 or Urban100 for instance? If so, how?

**Comment by krasserm** [comment]
Not out of the box. You'd need to implement your own custom Keras `Sequence` to provide training and testing data. See [data.py](https://github.com/krasserm/super-resolution/blob/master/data.py) how this is done for DIV2K. In case you want to use a dataset that doesn't contain downgraded images, you'd need to do bicubic downscaling etc yourself within the data provider.

**Comment by gitman88** [comment]
Ok! Thanks for the quick response, might look into it since Set5, Urban100, etc. are so common as benchmarks.

**Comment by PIjarihd** [comment]
@krasserm @gitman88 How should I prepare the data for custom data training? What pre-processing do I need? Can you explain stepwise or can you provide some link with the instruction?
