### ISSUE TITLE
InvalidArgumentError: input depth must be evenly divisible by filter depth: 4 vs 3 [Op:Conv2D]

### ISSUE THREAD

**Issue by nahidalam** [krasserm/super-resolution#84]
I cropped a high-resolution 200MB+ image to a smaller one on my Mac. It was originally a jpeg but Mac converts it to png after cropping. When I run it through the super resolution GANs example, I get the below error

```
InvalidArgumentError: input depth must be evenly divisible by filter depth: 4 vs 3 [Op:Conv2D]
```

Below code:

```
from model.srgan import generator

model = generator()
model.load_weights('all_weights/weights/srgan/gan_generator.h5')

lr = load_image('demo/who_is_this.png')
sr = resolve_single(model, lr)

plot_sample(lr, sr)
```

Is there any specific preprocessing I am missing?

**Comment by krasserm** [comment]
It seems that image conversion created a 4-channel png (RGB + alpha) but a 3-channel RGB input is required as input i.e. you need to convert the jpeg to a 3-channel png.

**Comment by nahidalam** [comment]
Thanks, that solves this specific error, although it does not actually enhance the image. 

Maybe I am not getting how the image data processing part actually works?

Below code:

```
from model.srgan import generator

model = generator()
model.load_weights('all_weights/weights/srgan/gan_generator.h5')

lr = load_image('demo/who_is_this.png')
lr = lr[...,:3]
sr = resolve_single(model, lr)

plot_sample(lr, sr)
```

**Comment by nahidalam** [comment]
Closing as the original issue is resolved
