### ISSUE TITLE
Train for 8x scale.

### ISSUE THREAD

**Issue by capogluuu** [krasserm/super-resolution#85]
![image](https://user-images.githubusercontent.com/59975090/120098253-754bcd80-c13d-11eb-9240-a5d5eff12471.png)

Train for 8x scale.

Hello, when I run your code, it gives the error "NotFoundError: .div2k/caches/DIV2K_train_HR.cache.data-00000-of-00001; No such file or directory [Op:IteratorGetNext]" for 8x scalemme status. How can I solve it? Thanks.

**Comment by krasserm** [comment]
After having set `scale = 8`, when running cells in section *Datasets* you should see an output like 

![Screenshot from 2021-05-30 15-14-31](https://user-images.githubusercontent.com/202907/120105624-fc0ea380-c159-11eb-8666-f491997a37fa.png)

The reported file should then be in the `.div2k` directory and training should work as expected.
