### ISSUE TITLE
Evaluation on RGB or YCbCr

### ISSUE THREAD

**Issue by gitman88** [krasserm/super-resolution#9]
I have a question regarding the evaluation of the models. In this implementation, just as in the EDSR and the WDSR papers, the models are evaluated with PSNR and SSIM on all three RGB-channels. However, in other papers, I have seen the evaluation being performed by converting the images from RGB to YCbCr and only evaluating the Y-channel (luminance).

So I guess I have two questions.

1) Do you know why different methods are used and if so if there are any pros/cons of the two approaches? 
2) Do you know if the methods differ on the PSNR/SSIM score? 

Thanks in advance!

**Comment by krasserm** [comment]
That's a good question I unfortunately cannot answer that i.e. never read about or worked with evaluation in YCbCr color space. But I think that evaluating only the Y-channel should give less accurate results as this more or less ignores color information. Hope that helps.

**Comment by gitman88** [comment]
Yeah, I have not found much information about it. But yes, probably less accurate results. Also a higher PSNR in general, at least from what I've experienced.
